### ISSUE TITLE
implementing the trait `Step` is not unsafe

### ISSUE THREAD

**Issue by mb720** [0xSilene/ramp-primes#3]
Hi and thanks for your crate!

I'm having trouble compiling its dependency RAMP. What I did so far:

* Add `ramp-primes = "0.4.0"` and `ramp = "0.5"` to my Cargo.toml
* `rustup toolchain install nightly; rustup default nightly`

When I call `cargo run`, I get this error:

      Compiling ramp v0.5.9
    error[E0199]: implementing the trait `Step` is not unsafe
        --> /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/ramp-0.5.9/src/int.rs:3697:1
         |
    3697 | / unsafe impl std::iter::Step for Int {
    3698 | |     fn steps_between(start: &Int, end: &Int) -> Option<usize> {
    3699 | |         let diff = (start - end).abs();
    3700 | |
    ...    |
    3715 | |     }
    3716 | | }
         | |_^

    For more information about this error, try `rustc --explain E0199`.
    error: could not compile `ramp` due to previous error

`cargo version` gives:

    cargo 1.57.0-nightly (d56b42c54 2021-09-27)

**Comment by AtropineTears** [comment]
I've had this issue for awhile now. No clue how to fix it.

I suggest you look at [num-primes](https://github.com/AtropineTears/num-primes) instead. It uses num as opposed to RAMP which does not use unsafe code like RAMP. Its maintained more than this crate and compiles.

Both crates also have the exact same API as num-primes is based on ramp-primes.

Hope this helps!
